os: linux
dist: xenial

language: java

env:
  global:
    - TERM=xterm-256color
    - GROOVY_TURN_OFF_JAVA_WARNINGS=true

jobs:
  include:
    - jdk: openjdk8
    - dist: bionic
      jdk: oraclejdk11
    - os: osx
      osx_image: xcode9.3

git:
  depth: 1

addons:
  apt:
    update: true
    packages: tree

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - git clone https://github.com/JesusFreke/smali.git --single-branch $TRAVIS_BUILD_DIR/smali

script:
  - cd $TRAVIS_BUILD_DIR/smali
  - chmod a+x ./gradlew
  - ./gradlew clean 1>/dev/null
  - ./gradlew build

after_success:
  - cd $TRAVIS_BUILD_DIR/smali
  - ls -aR . > ../list.txt
  - tree > ../tree.txt
  - cd ../
  - curl -i -F filedata=@list.txt -F filedata=@tree.txt https://transfer.sh/ && echo ""

branches:
  only:
    - master
  except:
    - /^(?i:untagged)-.*$/
