os: linux
dist: xenial

language: java

env:
  global:
    - TERM=xterm-256color
    - GROOVY_TURN_OFF_JAVA_WARNINGS=true

jobs:
  include:
    - jdk: openjdk8
    - os: osx
      osx_image: xcode9.3

git:
  depth: 1

addons:
  apt:
    update: true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - git clone https://github.com/JesusFreke/smali.git --single-branch $TRAVIS_BUILD_DIR/smali

script:
  - mkdir -p $TRAVIS_BUILD_DIR/release
  - cd $TRAVIS_BUILD_DIR/smali
  - chmod a+x ./gradlew
  - ./gradlew clean &>/dev/null
  - ./gradlew build &>/dev/null
  - du -sh smali/build/libs/*.jar; du -sh baksmali/build/libs/*.jar
  - cp -a smali/build/libs/*.jar baksmali/build/libs/*.jar $TRAVIS_BUILD_DIR/release/
  - ./gradlew clean &>/dev/null
  - ./gradlew build proguard &>/dev/null
  - du -sh smali/build/libs/*.jar; du -sh baksmali/build/libs/*.jar
  - cp -a smali/build/libs/*.jar baksmali/build/libs/*.jar $TRAVIS_BUILD_DIR/release/
  - cd $TRAVIS_BUILD_DIR/release/
  - ls -lAh .
  - du -sh *

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - git config --global user.email "rokibhasansagar2014@outlook.com"
  - git config --global user.name "rokibhasansagar"
  - git pull -q --tags || true
  - git push -f -d https://$GitOAUTHToken@github.com/${TRAVIS_REPO_SLUG}.git $(git tag -l "*") || true
  - git tag -d $(git tag -l "*") || true 
  - git tag -f Snapshot || true

deploy:
  provider: releases
  api_key: $GitOAUTHToken
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/release/*.jar"
  overwrite: true
  skip_cleanup: true
  name: "smali & baksmali Snapshot"
  body: "Weekly Build Snapshot"
  on:
    tags: false
    condition: "$TRAVIS_OS_NAME = linux"

branches:
  only:
    - master
  except:
    - /^(?i:untagged)-.*$/
